version: "3.6"

services:
  yivi:
    container_name: tosti-yivi
    image: ghcr.io/privacybydesign/irma:edge
    command: >
      server -v --requestors '{"tosti": {"auth_method": "token", "key": "${YIVI_TOKEN}"}}' -c /config.yml
    restart: always
    volumes:
      - ./config.yml:/config.yml
    environment:
      YIVI_TOKEN: ${YIVI_TOKEN}
