version: "3.6"

services:
  yivi:
    container_name: tosti-yivi
    image: ghcr.io/privacybydesign/irma:edge
    command: server -v -c /config.yml
    restart: always
    volumes:
      - ./config.yml:/config.yml
    networks:
      - tosti-yivi

networks:
    tosti-yivi:
        external: true
        name: caddy_reverseproxy
